matrix:
  include:
    - os: linux
      dist: focal
      arch:
        - arm64
      compiler: gcc
      addons:
        apt:
          packages:
            - libhts-dev
            - libtabixpp-dev 
            - libtabixpp0
script:
    - pkg-config --list-all
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build . --verbose
    - ctest --verbose
